- name: Schedule brew update
  ansible.builtin.cron:
    name: homebrew update
    minute: 0
    hour: 7
    job: brew update

- name: Schedule brew upgrade
  ansible.builtin.cron:
    name: homebrew upgrade
    minute: 0
    hour: 8
    job: brew upgrade

- name: Schedule brew cask upgrade
  ansible.builtin.cron:
    name: homebrew cask upgrade
    minute: 0
    hour: 9
    job: brew upgrade --cask
