- name: upgrade all casks
  community.general.homebrew_cask:
    upgrade_all: true

  # https://formulae.brew.sh/cask/
- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - 1password
      - cheatsheet
      - claude
      - clipy
      - cursor
      - github
      - google-chrome
      - google-cloud-sdk
      - raycast
      - slack
      - visual-studio-code
