- name: upgrade all casks
  community.general.homebrew_cask:
    upgrade_all: true
  ignore_errors: true

  # https://formulae.brew.sh/cask/
- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - 1password
      - cheatsheet
      - claude
      - claude-code
      - clipy
      - codex
      - cursor
      - github
      - google-chrome
      - google-cloud-sdk
      - iterm2
      # - logi-options+
      - raycast
      - slack
      - visual-studio-code
